project:
  type: manuscript
  # output-dir: _manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    number-sections: true
  pdf:
    documentclass: scrartcl
    toc: true
    number-sections: true
    colorlinks: true
    output-file: "index.pdf"
    biblio-title: "Bibliography"
    cite-method: biblatex
    number-offset: 1
    header-includes:
      - \usepackage{biblatex}
      - \usepackage{sectsty}
      - \sectionfont{\clearpage}
      - \ExecuteBibliographyOptions{sorting=none,defernumbers=true}
execute:
  freeze: auto