project:
  type: manuscript
  # output-dir: _manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    number-sections: true
  docx: default
  typst:
    toc: true
    number-sections: true
    columns: 2
    output-file: "index_typst.pdf"
    number-offset: 1
  jats: default
  pdf:
    documentclass: report
    toc: true
    number-sections: true
    colorlinks: true
    output-file: "index_pdf.pdf"
    biblio-title: "Bibliography"
    cite-method: biblatex
    number-offset: 1

execute:
  freeze: auto