# Acknowledgments {.unnumbered .unlisted}

Firstly I would like to express my gratitude to Tom van Tilburg, who helped me a lot at every step of the internship. From data management and processing to the architecture of the model, he brought a lot of new ideas and encouraged me to question my own. Brian de Vogel also deserves my heartfelt thanks for his ideas and his unconditional help regarding any practical and material matter. Together with Tom, they took from their time to supervise me every week, answer to any of my questions and introduce me to several geo-spatial topics that I knew nothing about beforehand.

Then I would like to thank the two people who made this internship possible in the first place. I am grateful to Henk Scholten, who supported my internship all along and enabled me to meet new people in several major institutions. A special thanks also to Rene Bruinink for his direct and sincere interest towards my spontaneous application, as well as for his transparency and honesty from the beginning of the internship discussion.

Finally I am sincerely thankful to the rest of the Research Team, Anne Blankert, Bert Temme, Kamiel Verhelst, Stefan de Graaf and Tim Ebben for warmly welcoming and integrating me to the team. Loïc de Jong also deserves a special thanks for his help regarding many practical matters and administrative tasks that were specific to living in the Netherlands. He also supported me a lot in my adaptation to this new country, even though it is not so different from France.

\tableofcontents
\listoffigures
